modLoader="javafml"
loaderVersion="[55,)"
license="mSLA v2.0"
issueTrackerURL="https://github.com/moritz-htk/music-delay-reducer/issues"
clientSideOnly=true

[[mods]]
    modId="music_delay_reducer"
    version="${version}"
    displayName="Music Delay Reducer"
    updateJSONURL="https://api.modrinth.com/updates/music-delay-reducer/forge_updates.json"
    displayURL="https://kyronis.net/mods/music-delay-reducer"
    logoFile="assets/music_delay_reducer/icon.png"
    authors="Kyronis"
    description='''This mod lets Minecraft music play more often.'''

[[dependencies.music_delay_reducer]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.music_delay_reducer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5, 1.22)"
    ordering="NONE"
    side="BOTH"