modLoader="javafml"
loaderVersion="[4)"
license="moritz_htk Software License Agreement (mSLA)"
issueTrackerURL="https://github.com/moritz-htk/Music-Delay-Reducer/issues"

[[mods]]
    modId="music_delay_reducer"
    version="${version}"
    displayName="Music Delay Reducer"
    updateJSONURL="https://api.modrinth.com/updates/music-delay-reducer/forge_updates.json?neoforge=only"
    displayURL="https://sites.google.com/view/moritz-htk/mods/music-delay-reducer"
    logoFile="icon.png"
    credits="LudoCrypt (Original Creator)"
    authors="moritz_htk"
    description='''This mod lets Minecraft music play more often.'''

[[mixins]]
    config="mixin.music_delay_reducer.json"

[[dependencies.music_delay_reducer]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.music_delay_reducer]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.music_delay_reducer]]
    modId="cloth_config"
    type="required"
    versionRange="[15.0.128,)"
    ordering="AFTER"
    side="BOTH"