modLoader="javafml"
loaderVersion="[4,)"
license="mSLA v2.0"
issueTrackerURL="https://github.com/moritz-htk/music-delay-reducer/issues"

[[mods]]
    modId="music_delay_reducer"
    version="${version}"
    displayName="Music Delay Reducer"
    updateJSONURL="https://api.modrinth.com/updates/music-delay-reducer/forge_updates.json?neoforge=only"
    displayURL="https://kyronis.net/mods/music-delay-reducer"
    logoFile="assets/music_delay_reducer/icon.png"
    authors="Kyronis"
    description='''This mod lets Minecraft music play more often.'''

[[mixins]]
    config="mixin.music_delay_reducer.json"

[[dependencies.music_delay_reducer]]
    modId="neoforge"
    type="required"
    versionRange="[21.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.music_delay_reducer]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5, 1.22)"
    ordering="NONE"
    side="BOTH"